config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks, only:[:create, :destroy]
  end

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	validates :title, 
	presence: { message: "入力してください"},
	length: { minimum: 3, message: "短すぎです" }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true
  scope :unfinished, -> {where(done: false) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
    redirect_to projects_path

    else
    	render 'new'
    end
    	
  end

  def edit
  end

  def update    
    if @project.update(project_params)
    	redirect_to projects_path

    else
    	render 'edit'
    end

  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end
  	
  private 

    def project_params
    	params[:project].permit(:title)
    end

    def set_project
      @project = Project.find(params[:id])
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
  	render nothing: true
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
  end
  	
  private 
    def task_params
      params[:task].permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= image_tag "logo.png" %>

<%= yield %>

<%= link_to "Home", "/" %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <% if @project.errors.any? %>
    <%= @project.errors.messages[:title][0] %>
    <%  end %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
      <% @projects.each do |project| %>
      <li>
      <%= link_to project.title, project_path(project.id) %> (<%= project.tasks.unfinished.count %>/<%= project.tasks.count %>)
      <%= link_to "[Edit]", edit_project_path(project.id) %>	
      <%= link_to "[Delete]", project_path(project.id),method: :delete, data:{ comfirm: "Are you sure?" } %>

      </li>
      <% end %>
</ul>

<p><%= link_to "Add New", new_project_path %></p>

app/views/projects/new.html.erb
<h1>Add New</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.title%></h1>

<ul>
	<% @project.tasks.each do |task| %>
	<li>
      <%= check_box_tag '', '', task.done, {'data-id' => task.id, 'data-project_id' => task.project_id} %>
	  <%= task.title %>
	  <%= link_to "[Delete]", project_task_path(task.project_id, task.id),method: :delete, data:{ comfirm: "Are you sure?" } %>	
	</li>
	<% end %>
    <li>
    	<%= form_for [@project, @project.tasks.build] do |f| %>
        <%= f.text_field :title %>
        <%= f.submit %>
        <% end %>
    </li>
</ul>


<script>
$(function() {
  $("input[type=checkbox]").click(function(){
    $.post('/projects/'+$(this).data('project_id')+'/tasks/'+$(this).data('id')+'/toggle');
  });
});	

</script>